---
- name: Upgrade and reboot catinthehat
  hosts: catinthehat
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes
    - name: Upgrade all packages
      apt:
        upgrade: dist
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
    - name: Reboot if necessary
      reboot:
        reboot_timeout: 600
      when: reboot_required.stat.exists
- name: Upgrade and reboot thing1 (Internet disruption expected)
  hosts: thing1
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes
    - name: Upgrade all packages
      apt:
        upgrade: dist
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
    - name: Reboot if necessary
      reboot:
        reboot_timeout: 600
      when: reboot_required.stat.exists
- name: Upgrade and reboot thing2 (Ansible host)
  hosts: thing2
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes
    - name: Upgrade all packages
      apt:
        upgrade: dist
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
    - name: Reboot if necessary
      reboot:
        reboot_timeout: 600
      when: reboot_required.stat.exists
