---
- name: Run update with expect and handle confirmation
  hosts: all
  become: yes
  tasks:
    - name: Ensure Python3 and pip are installed
      ansible.builtin.package:
        name:
          - python3
          - python3-pip
        state: present

    - name: Ensure pexpect is installed
      ansible.builtin.pip:
        name: pexpect
        state: present

    - name: Run 'update' command with expect to auto-confirm "Proceed?"
      ansible.builtin.expect:
        command: update
        responses:
          'Proceed\?': '\r'
      register: update_result
      failed_when: >
        update_result.rc != 0 or
        (update_result.stdout is defined and (
            'error' in update_result.stdout.lower() or
            'failed' in update_result.stdout.lower())
        )
      changed_when: >
        update_result.stdout is defined and (
            'updated' in update_result.stdout.lower() or
            'installed' in update_result.stdout.lower())
