---
- name: Run update and handle interactive prompt
  hosts: update_cmd
  become: true
  gather_facts: false

  pre_tasks:
    - name: Ensure python3-pexpect is installed
      apt:
        name: python3-pexpect
        state: present
        update_cache: yes

  tasks:
    - name: Run update and handle prompt
      expect:
        command: update
        responses:
          '.*Proceed\?.*': '\r'
        timeout: 90
      register: update_result
      changed_when: "'✓ Updated' in update_result.stdout"
      failed_when: "'error' in update_result.stdout.lower()"

    - name: Show update command output
      debug:
        var: update_result.stdout

