---
- name: Run update command and handle interactive prompt
  hosts: all
  become: yes
  tasks:
    - name: Run 'update' command with expect to auto-confirm "Proceed?"
      expect:
        command: update
        responses:
          'Proceed\?': '\r'
      register: update_result
      failed_when:
        - update_result.rc != 0
        - "'error' in update_result.stdout.lower() or 'failed' in update_result.stdout.lower()"
      changed_when: "'updated' in update_result.stdout.lower() or 'installed' in update_result.stdout.lower()"
