---
- name: Run update and check for success
  hosts: all
  become: yes
  tasks:
    - name: Run 'update' command and capture output
      ansible.builtin.shell: "echo | update"
      register: update_result
      changed_when: "'✓ Updated' in update_result.stdout"

    - name: Fail if update was not successful
      ansible.builtin.fail:
        msg: "Update did not succeed: {{ update_result.stdout | default('No output') }}"
      when: "'✓ Updated' not in update_result.stdout"
