---
- name: Upgrade Debian Portainer hosts and reboot
  hosts: portainer
  become: yes
  serial: 1  # Update and reboot hosts one by one to avoid downtime
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot if necessary (excluding control node)
      reboot:
        reboot_timeout: 600
      when: reboot_required.stat.exists and inventory_hostname != "management"
# reboot management(ansible) last
- name: Reboot Ansible Control Node last
  hosts: management
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot Ansible Control Node
      reboot:
        reboot_timeout: 600
      when: reboot_required.stat.exists
